### ISSUE TITLE
Data endianness problem (IDFGH-13693)

### ISSUE THREAD

**Issue by ForgetCSX** [espressif/esp-modbus#72] opened 2024-09-13 01:26 UTC
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Provided a clear description of your suggestion.
- [X] Included any relevant context or examples.

### Issue or Suggestion Description

I encountered a format issue with the data endianness when using this repository.
![image](https://github.com/user-attachments/assets/b2d623e9-86e6-4112-bd3b-677644fb9f33)
![image](https://github.com/user-attachments/assets/7ed04d3e-2777-4f64-9f95-c8aad125640e)
When I read the holding register at address 0, the data returned to me is 85 1F 3F AB
Converting 1.34 through dotted hexadecimal converter the single precision float big endian format I get is 3F AB 85 1E
The float little endian format is 1E 85 AB 3F
This will cause my modbus master device to not recognize the received data

This is the data online converter I use
https://www.asciim.cn/hex/float.html

There is another question. I use the 06 command to write a single register. In the same way, I still operate the register at address 0.
![image](https://github.com/user-attachments/assets/37163c83-859b-4b35-8f5c-f14499646cb3)
As you can see, the writing should be successful, and the data returned to me is also 100, but when printing on the slave machine, there is still no change.
![image](https://github.com/user-attachments/assets/91dfa1d1-e847-4f79-9651-602ca022d3e3)

**Comment by alisitsyn** [comment] 2024-09-16 08:16
@ForgetCSX,

The frame logger shows the raw ADU of Modbus frame. As per [Modbus specification](https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf):
![image](https://github.com/user-attachments/assets/7b17a645-1a73-4245-92d7-e42ac159f3c4).
This means you should not expect the same order of the data as you described above because the Modbus standard standard does not prescribe how the extended data types mapping and it can be performed differently by device vendors and software. The esp-modbus Slave by default converts the 32-bit data from `big-endian` to the 'Little-endian byte swap' format understandable by compiler.
However, the esp-modbus supports [the data conversion functions](https://docs.espressif.com/projects/esp-modbus/en/latest/esp32/applications_and_references.html#modbus-endianness-conversion-api-reference) and you can convert the data to the format that is needed for your particular Slave application. The extended types support can be enabled by `CONFIG_FMB_EXT_TYPE_SUPPORT=y` in the kconfig menu. 
![image](https://github.com/user-attachments/assets/6e384afc-a8c4-4917-8698-a4604ae52e43)

See the [esp-modbus extended datatypes](https://docs.espressif.com/projects/esp-modbus/en/latest/esp32/overview_messaging_and_mapping.html#mapping-of-complex-data-types), [Modbus Endianness Conversion API Reference](https://docs.espressif.com/projects/esp-modbus/en/latest/esp32/applications_and_references.html#modbus-endianness-conversion-api-reference), [example of conversion API](https://github.com/espressif/esp-modbus/blob/master/test/serial/mb_serial_slave/main/slave.c#L87). If you are using the esp-modbus master with your slaves, you can configure [the master to use appropriate format option](https://docs.espressif.com/projects/esp-modbus/en/latest/esp32/master_api_overview.html#id3) to work with your slave and the extended data conversion will be performed automatically by master in this case.

**Comment by ForgetCSX** [comment] 2024-09-16 08:58
@alisitsyn Thank you for your reply. I understand. Generally speaking, the problem is the data format. I didn’t know where to adjust it at first. I can adjust the byte order and it will be no problem. Now there is no doubt.

**Comment by alisitsyn** [comment] 2024-09-30 07:22
The issue is closed as explained.

**Closed by alisitsyn** 2024-09-30 07:22 UTC
Labels: Status: In Progress
